site_name: OmniSpatial Docs
site_url: https://omnispatial.org/docs
repo_url: https://github.com/omnispatial/omnispatial
theme:
  name: material
nav:
  - Overview: index.md
  - Quickstart:
      - CLI Quickstart: quickstart.md
      - Examples: examples.md
  - Architecture: architecture.md
  - Benchmarking: benchmarking.md
  - Benchmark Dashboard: benchmark-dashboard.md
  - Developer Guide: developer-guide.md
  - API: api.md
docs_dir: docs
